# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('famale', '女')], default='male', max_length=6),
        ),
    ]
